name: Java CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Build with Maven
      run: mvn clean verify
      
    - name: Upload Checkstyle Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: checkstyle-report
        path: target/checkstyle-result.xml
        
    - name: Upload PMD Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: pmd-report
        path: target/pmd.xml
        
    - name: Upload JaCoCo Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: jacoco-report
        path: target/site/jacoco/