# Nombre del workflow
name: Validación de Pull Request y Despliegue de Reportes

# Descripción: Este workflow valida pull requests en la rama 'develop' con Checkstyle, PMD y umbral mínimo de cobertura JaCoCo,
# luego genera y despliega reportes completos en GitHub Pages.

# Definición de permisos para el workflow, siguiendo el principio de privilegio mínimo
permissions:
  contents: read      # Permiso para leer el contenido del repositorio
  pages: write        # Permiso para escribir en GitHub Pages
  id-token: write     # Permiso para autenticación con GitHub Pages

# Evento que dispara el workflow
on:
  pull_request:
    branches:
      - develop
    types:
      - opened          # Se ejecuta al abrir un PR
      - synchronize     # Se ejecuta al actualizar un PR
      - reopened        # Se ejecuta al reabrir un PR

# Cancelación de ejecuciones previas para optimizar recursos
concurrency:
  group: pr-validation-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  # Job para validaciones estrictas (se detiene si falla Checkstyle, PMD o no se cumple el umbral de cobertura)
  validate:
    name: Validaciones Estrictas
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Obtiene el historial completo para análisis de cambios

      # Paso 2: Configurar JDK 11
      - name: Configurar JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'          # Versión especificada en el pom.xml
          distribution: 'temurin'     # Distribución confiable de JDK
          cache: 'maven'              # Habilita caché para dependencias de Maven

      # Paso 3: Validar formato del código con Checkstyle
      - name: Validar formato con Checkstyle
        run: mvn checkstyle:check -B -f pom.xml
        # Falla si hay violaciones de estilo según google_checks.xml

      # Paso 4: Ejecutar pruebas y verificar cobertura mínima
      - name: Verificar cobertura de código
        run: mvn test jacoco:check -B -f pom.xml
        # Falla si no se alcanza el umbral mínimo de cobertura definido en pom.xml

      # Paso 5: Validar reglas de PMD
      - name: Validar reglas de PMD
        run: mvn pmd:check -B -f pom.xml
        # Falla si hay violaciones de las reglas PMD configuradas

  # Job para generación de reportes y despliegue (siempre se ejecuta después de validate)
  deploy-reports:
    name: Generar y Desplegar Reportes
    runs-on: ubuntu-latest
    needs: validate
    if: always()  # Siempre se ejecuta, incluso si validate falló
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Paso 2: Configurar JDK 11
      - name: Configurar JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      # Paso 3: Generar reporte de cobertura JaCoCo
      - name: Generar reporte JaCoCo
        run: mvn jacoco:report -B -f pom.xml
        # Genera reporte HTML de cobertura independientemente del umbral

      # Paso 4: Generar reporte de Checkstyle
      - name: Generar reporte Checkstyle
        run: mvn checkstyle:checkstyle -B -f pom.xml
        # Genera reporte HTML de Checkstyle aunque haya violaciones

      # Paso 5: Generar reporte de PMD
      - name: Generar reporte PMD
        run: mvn pmd:pmd -B -f pom.xml
        # Genera reporte HTML de PMD aunque haya violaciones

      # Paso 6: Generar reporte de Javadoc y consolidar con Maven Site
      - name: Generar reportes consolidados
        run: mvn site -B -f pom.xml
        # Genera sitio con todos los reportes integrados

      # Paso 7: Subir artefacto para Pages
      - name: Subir reportes para despliegue
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'target/site'

      # Paso 8: Desplegar en GitHub Pages
      - name: Desplegar reportes
        id: deployment
        uses: actions/deploy-pages@v4