# Nombre del workflow
name: Deploy JAR al hacer pull en main

# Se ejecuta cuando se hace push a main (después del merge desde release)
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-jar:
    name: Generar y Publicar JAR
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout del código
        uses: actions/checkout@v4

      # Paso 2: Configurar Java 11
      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Paso 3: Construir el proyecto y generar el JAR
      - name: Compilar y empaquetar JAR
        run: mvn clean package -DskipTests

      # Paso 4: Subir el JAR como artefacto descargable
      - name: Subir JAR como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: target/*.jar